/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GuestbookRouteImport } from './routes/guestbook'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewslettersIdRouteImport } from './routes/newsletters.$id'
import { Route as ConfirmTokenRouteImport } from './routes/confirm.$token'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminSubscribersRouteImport } from './routes/admin.subscribers'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminNewslettersRouteImport } from './routes/admin.newsletters'
import { Route as AdminCommentsRouteImport } from './routes/admin.comments'
import { Route as AdminNewslettersNewRouteImport } from './routes/admin.newsletters.new'
import { Route as AdminContentProjectRouteImport } from './routes/admin.content.project'
import { Route as AdminContentBlogRouteImport } from './routes/admin.content.blog'
import { Route as AdminContentBlogNewRouteImport } from './routes/admin.content.blog.new'
import { Route as AdminContentBlogSlugRouteImport } from './routes/admin.content.blog.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestbookRoute = GuestbookRouteImport.update({
  id: '/guestbook',
  path: '/guestbook',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewslettersIdRoute = NewslettersIdRouteImport.update({
  id: '/newsletters/$id',
  path: '/newsletters/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmTokenRoute = ConfirmTokenRouteImport.update({
  id: '/confirm/$token',
  path: '/confirm/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewslettersRoute = AdminNewslettersRouteImport.update({
  id: '/newsletters',
  path: '/newsletters',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewslettersNewRoute = AdminNewslettersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminNewslettersRoute,
} as any)
const AdminContentProjectRoute = AdminContentProjectRouteImport.update({
  id: '/content/project',
  path: '/content/project',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentBlogRoute = AdminContentBlogRouteImport.update({
  id: '/content/blog',
  path: '/content/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentBlogNewRoute = AdminContentBlogNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminContentBlogRoute,
} as any)
const AdminContentBlogSlugRoute = AdminContentBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminContentBlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/guestbook': typeof GuestbookRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/terms': typeof TermsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/newsletters': typeof AdminNewslettersRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/confirm/$token': typeof ConfirmTokenRoute
  '/newsletters/$id': typeof NewslettersIdRoute
  '/admin/content/blog': typeof AdminContentBlogRouteWithChildren
  '/admin/content/project': typeof AdminContentProjectRoute
  '/admin/newsletters/new': typeof AdminNewslettersNewRoute
  '/admin/content/blog/$slug': typeof AdminContentBlogSlugRoute
  '/admin/content/blog/new': typeof AdminContentBlogNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/guestbook': typeof GuestbookRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/terms': typeof TermsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/newsletters': typeof AdminNewslettersRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/confirm/$token': typeof ConfirmTokenRoute
  '/newsletters/$id': typeof NewslettersIdRoute
  '/admin/content/blog': typeof AdminContentBlogRouteWithChildren
  '/admin/content/project': typeof AdminContentProjectRoute
  '/admin/newsletters/new': typeof AdminNewslettersNewRoute
  '/admin/content/blog/$slug': typeof AdminContentBlogSlugRoute
  '/admin/content/blog/new': typeof AdminContentBlogNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/guestbook': typeof GuestbookRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/terms': typeof TermsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/newsletters': typeof AdminNewslettersRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/confirm/$token': typeof ConfirmTokenRoute
  '/newsletters/$id': typeof NewslettersIdRoute
  '/admin/content/blog': typeof AdminContentBlogRouteWithChildren
  '/admin/content/project': typeof AdminContentProjectRoute
  '/admin/newsletters/new': typeof AdminNewslettersNewRoute
  '/admin/content/blog/$slug': typeof AdminContentBlogSlugRoute
  '/admin/content/blog/new': typeof AdminContentBlogNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/guestbook'
    | '/login'
    | '/privacy'
    | '/projects'
    | '/terms'
    | '/admin/comments'
    | '/admin/newsletters'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/blog/$slug'
    | '/confirm/$token'
    | '/newsletters/$id'
    | '/admin/content/blog'
    | '/admin/content/project'
    | '/admin/newsletters/new'
    | '/admin/content/blog/$slug'
    | '/admin/content/blog/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/guestbook'
    | '/login'
    | '/privacy'
    | '/projects'
    | '/terms'
    | '/admin/comments'
    | '/admin/newsletters'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/blog/$slug'
    | '/confirm/$token'
    | '/newsletters/$id'
    | '/admin/content/blog'
    | '/admin/content/project'
    | '/admin/newsletters/new'
    | '/admin/content/blog/$slug'
    | '/admin/content/blog/new'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/guestbook'
    | '/login'
    | '/privacy'
    | '/projects'
    | '/terms'
    | '/admin/comments'
    | '/admin/newsletters'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/blog/$slug'
    | '/confirm/$token'
    | '/newsletters/$id'
    | '/admin/content/blog'
    | '/admin/content/project'
    | '/admin/newsletters/new'
    | '/admin/content/blog/$slug'
    | '/admin/content/blog/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  GuestbookRoute: typeof GuestbookRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ProjectsRoute: typeof ProjectsRoute
  TermsRoute: typeof TermsRoute
  ConfirmTokenRoute: typeof ConfirmTokenRoute
  NewslettersIdRoute: typeof NewslettersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guestbook': {
      id: '/guestbook'
      path: '/guestbook'
      fullPath: '/guestbook'
      preLoaderRoute: typeof GuestbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletters/$id': {
      id: '/newsletters/$id'
      path: '/newsletters/$id'
      fullPath: '/newsletters/$id'
      preLoaderRoute: typeof NewslettersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm/$token': {
      id: '/confirm/$token'
      path: '/confirm/$token'
      fullPath: '/confirm/$token'
      preLoaderRoute: typeof ConfirmTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/newsletters': {
      id: '/admin/newsletters'
      path: '/newsletters'
      fullPath: '/admin/newsletters'
      preLoaderRoute: typeof AdminNewslettersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/newsletters/new': {
      id: '/admin/newsletters/new'
      path: '/new'
      fullPath: '/admin/newsletters/new'
      preLoaderRoute: typeof AdminNewslettersNewRouteImport
      parentRoute: typeof AdminNewslettersRoute
    }
    '/admin/content/project': {
      id: '/admin/content/project'
      path: '/content/project'
      fullPath: '/admin/content/project'
      preLoaderRoute: typeof AdminContentProjectRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/blog': {
      id: '/admin/content/blog'
      path: '/content/blog'
      fullPath: '/admin/content/blog'
      preLoaderRoute: typeof AdminContentBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/blog/new': {
      id: '/admin/content/blog/new'
      path: '/new'
      fullPath: '/admin/content/blog/new'
      preLoaderRoute: typeof AdminContentBlogNewRouteImport
      parentRoute: typeof AdminContentBlogRoute
    }
    '/admin/content/blog/$slug': {
      id: '/admin/content/blog/$slug'
      path: '/$slug'
      fullPath: '/admin/content/blog/$slug'
      preLoaderRoute: typeof AdminContentBlogSlugRouteImport
      parentRoute: typeof AdminContentBlogRoute
    }
  }
}

interface AdminNewslettersRouteChildren {
  AdminNewslettersNewRoute: typeof AdminNewslettersNewRoute
}

const AdminNewslettersRouteChildren: AdminNewslettersRouteChildren = {
  AdminNewslettersNewRoute: AdminNewslettersNewRoute,
}

const AdminNewslettersRouteWithChildren =
  AdminNewslettersRoute._addFileChildren(AdminNewslettersRouteChildren)

interface AdminContentBlogRouteChildren {
  AdminContentBlogSlugRoute: typeof AdminContentBlogSlugRoute
  AdminContentBlogNewRoute: typeof AdminContentBlogNewRoute
}

const AdminContentBlogRouteChildren: AdminContentBlogRouteChildren = {
  AdminContentBlogSlugRoute: AdminContentBlogSlugRoute,
  AdminContentBlogNewRoute: AdminContentBlogNewRoute,
}

const AdminContentBlogRouteWithChildren =
  AdminContentBlogRoute._addFileChildren(AdminContentBlogRouteChildren)

interface AdminRouteChildren {
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminNewslettersRoute: typeof AdminNewslettersRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  AdminContentBlogRoute: typeof AdminContentBlogRouteWithChildren
  AdminContentProjectRoute: typeof AdminContentProjectRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCommentsRoute: AdminCommentsRoute,
  AdminNewslettersRoute: AdminNewslettersRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  AdminContentBlogRoute: AdminContentBlogRouteWithChildren,
  AdminContentProjectRoute: AdminContentProjectRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  GuestbookRoute: GuestbookRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ProjectsRoute: ProjectsRoute,
  TermsRoute: TermsRoute,
  ConfirmTokenRoute: ConfirmTokenRoute,
  NewslettersIdRoute: NewslettersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
